modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/kyleplo/biotania/issues"
license = "MIT"

[[mods]]
modId = "biotania"
version = "${version}"
displayName = "Biotania"
displayURL="https://modrinth.com/mod/botania"
authors = "kyleplo"
description = '''
Biome mod adding biomes themed around Botania and using its blocks
'''
logoFile = "assets/biotania/logo.png"

[[dependencies.biotania]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biotania]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.4)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biotania]]
modId = "biolith"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biotania]]
modId = "botania"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
