modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/kyleplo/biotania/issues"
license = "MIT"

[[mods]]
modId = "biotania"
version = "${version}"
displayName = "Biotania"
displayURL="https://modrinth.com/mod/biotania"
authors = "kyleplo"
description = '''
Biome mod adding biomes themed around Botania and using its blocks
'''
logoFile = "assets/biotania/logo.png"

[[dependencies.biotania]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biotania]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,1.20.4)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biotania]]
modId = "biolith"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biotania]]
modId = "botania"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
